### PR TITLE
Refactoring how guard error types are provided

### PR DESCRIPTION
**Pull request by ryan-summers**
This PR refactors how custom guard errors are specified.

Instead of specifying the custom type in the `statemachine!` macro, the guard error is specified as an associated-type of the trait object.

This makes guard errors more usable for cases when the concrete type of the error is unknown at the declaration of the statemachine (e.g. errors with generic parameters).

I've also removed the `derive(Copy, Clone, Eq, PartialEq)` for `enum Error`. There are many types of `GuardErrors` that would not necessarily implement all of these traits. Since the user is still able to manually implement these traits outside of the declaration, it seems better to be less strict about what types of `GuardError` are acceptable.

### CODE REVIEW

**Comment by ryan-summers** [comment]
@korken89 / @pleepleus Would either of you be able to review this change? I'd like to use this to release a change to `minimq`

**Comment by pleepleus** [comment]
I think I'll have time this week.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dzimmanck** [comment]
@ryan-summers, I am checking it out

**Comment by dzimmanck** [comment]
@ryan-summers,

Looks pretty good to me.  I agree that removing the heavy handed derive on the GuardError makes sense. 
My only feedback is that I think the examples/guard_custom_error.rs file could use some improvement.  Most other example files have some code with assertion checks in fn main() {} not only for testing but also to provide some better context to potential users on how a particular feature is useful.  However, this was like this even before your PR so I won't gate.  If you improve it that would be a bonus.

@MathiasKoch, this does slightly change the syntax for how GuardErrors are used so can cause breaking changes.  I think that simply means that this would need to be a 0.6.0 release of code, but I would like your take as it looks like you are the original author of the GuardError feature.

There is also a check fail int he link checker that doesn't make sense to me as I don't see any links you added in the documentation.  I will look into that.

**Comment by MathiasKoch** [comment]
Without having reviewed the actual implementation yet, I think this sounds like a great addition :+1:

**Comment by dzimmanck** [comment]
Looks like the use of LinkChecker is no longer recommended for GitHub actions in favor of [lynchee](https://github.com/lycheeverse/lychee-action).  I think we should just update the docs.yml file and see if that fixes the tests.  I will do as soon as I get a chance unless someone else wants to do it.

**Comment by dzimmanck** [comment]
@ryan-summers.  I create a separate PR  #46 to fix the link checker.  If that gets accepted and you merge it into this, that should fix your CI tests.

**Comment by dzimmanck** [comment]
@ryan-summers,

We have a chicken and egg problem in that I appear to be the only active reviewer right now for this project that can approve PRs and I am not allowed to approve my own PR, so my fix to the link checker is not getting merged in.

I think you should just remove the link check in the actions as part of this PR so that the CI tests pass.  I will then approve and get this thing moving.

**Comment by Yatekii** [comment]
Al done :)

**Review by Yatekii — APPROVED** [review]

**Pull request merged**
