### PR TITLE
Add custom attributes for States and Events enum

### PR DESCRIPTION
**Pull request by prabhpreet**
Use `states_attr` and `events_attr` to add custom attributes (eg. #[allow(...)])

Example:

```rust
#![deny(non_camel_case_types)]
    statemachine! {
        transitions: {
            *State1 + tostate2 = State2,
            State2 + tostate3 / increment_count = State3
        },
        derive_states: [Debug, Clone, Copy],
        states_attr: #[non_exhaustive] #[repr(u8)],
        events_attr: #[derive(Debug)] #[allow(non_camel_case_types)]
    }
```

### CODE REVIEW

**Review by ryan-summers — CHANGES_REQUESTED** [review]
I would prefer if we just completely replaced the `derive_*` fields and replaced them with these `*_attributes` fields instead. Having them spread across different implementations seems messy.

**Comment by prabhpreet** [comment]
> I would prefer if we just completely replaced the `derive_*` fields and replaced them with these `*_attributes` fields instead. Having them spread across different implementations seems messy.

I agree this is better, I'll remove the `derive_*` fields, will be a breaking change

> Alternatively, are there some common-sense attributes that you think should be applied to states/events?

My motivation was to customize the structs when serializing using serde. Since this is also targeted towards `no_std`, maybe it is better for the users to decide?

**Comment by ryan-summers** [comment]
Breaking changes are fine. We've done lots of them recently, and I try to release as often as required :) The migration tends to be quite easy.

**Comment by prabhpreet** [comment]
@ryan-summers Made the changes including tests, and docs, please feel free to review/edit

**Review by ryan-summers — COMMENTED** [review]
Mind just updating the changelog? Looks like a nice clean change set - nice work :)

**Review by ryan-summers — APPROVED** [review]

**Pull request merged**
