### PR TITLE
Can specify initial state when creating Statemachine

### PR DESCRIPTION
**Pull request by videni**
For issue [unable to initialize statemachine with current state](https://github.com/korken89/smlang-rs/issues/19)

### CODE REVIEW

**Comment by korken89** [comment]
Thanks for the addition!

One thing I'd like you to change, make this a new `new_with_state` or something like that and without the `Option`, to not break the old API.

**Comment by korken89** [comment]
Please rebase on master as well to get the tests to pass.

**Comment by videni** [comment]
@korken89  , good idea,  added.

**Comment by korken89** [comment]
Final small comment, could you add a line of documentation on the method?

**Comment by videni** [comment]
@korken89 , sure

**Comment by korken89** [comment]
Thanks for the update!
It seems though that the fmt CI does not pass, can you have a look?

**Comment by videni** [comment]
@korken89 , sorry, it seems correct for me, can you check why please?

**Comment by korken89** [comment]
It seems you need to run cargo fmt

**Comment by videni** [comment]
@korken89, can you merge it please?

**Comment by korken89** [comment]
Hi, it seems you still need to run `cargo fmt`.
There are 2 lines with trailing white-space which is causing the CI to fail.

**Comment by korken89** [comment]
I'll merge it and fix it from my side.

**Pull request merged**
